### ISSUE TITLE
Does flowpipe have/need/want a logo?

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#101]
In the end of the month, I will give a talk at a local Data Science meetup on how I use flowpipe to orchestrate microservices.I will of course advertise flowpipe!

I think it would be great to have a logo to show, so if there is one in the works, or if someone has the skills to create one, that would be really amazing.

**Comment by PaulSchweizer** [comment]
Super cool! Thanks @neuneck! 
There is no logo in the works currently but under these circumstances I'll dust up my graphic design skills and try to come up with something, will keep you posted.  
Will it be possible to see your slides or any of your information online?

**Comment by neuneck** [comment]
Yes, of course. The talk I give is public anyways, so I don't see any reason not to upload the slides somewhere!
I'm really looking forward to the logo :)

**Comment by PaulSchweizer** [comment]
I toyed around a bit, let me know which one you like best (if any), 
**1**
![logo1](https://user-images.githubusercontent.com/5315460/68542505-96a76600-03ad-11ea-83e3-a12ebdea27c8.png)
**2**
![logo2](https://user-images.githubusercontent.com/5315460/68542506-96a76600-03ad-11ea-83eb-409e5ba191fb.png)
**3**
![logo3](https://user-images.githubusercontent.com/5315460/68542507-973ffc80-03ad-11ea-849f-e038b965f84e.png)
**4**
![logo4](https://user-images.githubusercontent.com/5315460/68542509-973ffc80-03ad-11ea-9c3a-58493a717b6a.png)
**5**
![logo5](https://user-images.githubusercontent.com/5315460/68542510-973ffc80-03ad-11ea-80f1-00665e432d64.png)
**6**
![logo6](https://user-images.githubusercontent.com/5315460/68542511-97d89300-03ad-11ea-909e-8c64f3b55369.png)
**7**
![logo7](https://user-images.githubusercontent.com/5315460/68542512-97d89300-03ad-11ea-8bce-7a151337bd73.png)
**8**
![logo8](https://user-images.githubusercontent.com/5315460/68542513-97d89300-03ad-11ea-9784-b09c0f97ca01.png)
**9**
![logo9](https://user-images.githubusercontent.com/5315460/68542514-97d89300-03ad-11ea-9d81-c3a538fc0948.png)
**10**
![logo10](https://user-images.githubusercontent.com/5315460/68542515-98712980-03ad-11ea-93ed-4e69bcf84163.png)
**11**
![logo11](https://user-images.githubusercontent.com/5315460/68542516-98712980-03ad-11ea-87b4-6b5d85ee2c66.png)
**12**
![logo12](https://user-images.githubusercontent.com/5315460/68542517-98712980-03ad-11ea-9496-d25a28153e61.png)
**13**
![logo13](https://user-images.githubusercontent.com/5315460/68542518-98712980-03ad-11ea-9e50-d1d16a8c2644.png)

**Comment by neuneck** [comment]
I like deisgns 1 and 9, with a preference on 9. 

Nr. 9 looks clean and dynamic to me, with the arrow pointing to the "o" and the box around the "wpipe" hinting at flow-based programming elements.

Nr. 1 has those elements more pronounced, but to me the boxes in front of the "f" make it less sleek.

Thank you a lot for the work that went into those! I hope that a logo will help us grow this project even further.

**Comment by PaulSchweizer** [comment]
Thanks for your input, I had a hard time choosing one. 
I uploaded Nr. 9 as logo.png, ready for use. Let me know if you need a different format or anything and good luck with the presentation!

**Comment by neuneck** [comment]
@PaulSchweizer The slides for my talk tomorrow are done. You can find them at:
https://www.slideshare.net/secret/r4OjQTjsQK2Mer

**Comment by PaulSchweizer** [comment]
Very cool, thanks for sharing! I hope your presentation went well. I'll take inspiration from it if I ever give a presentation on flowpipe :)

**Comment by neuneck** [comment]
Thank you. It went well indeed and people were genuinely interested in this approach. I think the great logo also really helped to give the project a "face" people can connect with!
