### ISSUE TITLE
Pattern for dynamic plug names

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#106]
When I build my nodes, I use the subclassing `INode` API, since I have to be able to pickle my graph at some later point, and the nodes are defined across various client packages.

In that API, it was tricky to define multiple nodes of the same type, while allowing for different input/output plug names. That's because the plug names have to align with keyword arguments of the `compute` function. As an example use case, when we do a face match, we have to do the same operations for the two images to match, and naming nodes and plugs in an explicit and human-readable manner makes things much easier. This resulted in me using the following pattern a few times, in different node types:
```python
from flowpipe import INode, InputPlug, OutputPlug


class FileReader(INode):
    """Reads a file from the filesystem."""

    def __init__(self, input_name, output_name, reading_client, **kwargs):
        """Set up a file reader node.

        Parameters
        ----------
        input_name : str
            The name of the input
        output_name : str
            The name of the output
        reading_client : NectClient
            The client that performs the reading of the image
        kwargs
            kwargs are passed on the the INode base class

        """
        super().__init__(**kwargs)

        self.input_name = input_name
        InputPlug(input_name, self)

        self.output_name = output_name
        OutputPlug(output_name, self)

        self.reading_client = reading_client

    def compute(self, **kwargs):
        """Read the file at the given path.

        Parameters
        ----------
        self.input_name : str, a valid path
            The name of this argument needs to be set in the constructor.

        """
        try:
            path = kwargs.pop(self.input_name)
        except KeyError:
            # log
            raise
        if kwargs:
            # log.warn("Excessive keyword arguments in node ....")
            pass

        bytestring = self.reading_client.read(path)

        # log
        return {self.output_name: bytestring}
```
 The "trick" is to allow - on the surface - for arbitrary keyword arguments in the `compute` function, and then being careful about which ones are used and if there are surplus arguments.

I just wanted to share this pattern with you - if you find it useful, by all means, use it! If you find it very useful, we could make an example out of it. And of course, if you find it problematic for some reason, do tell me!

**Comment by PaulSchweizer** [comment]
Nice, sort of like an on the fly factory, that's why you wanted to pickle the input args to the `__init__` in an earlier ticket I assume?
Thanks for sharing and yes, if you find the time, please add it to the example files
