### ISSUE TITLE
Use more pytest fixtures

### ISSUE THREAD

**Issue by Anton-4** [PaulSchweizer/flowpipe#109]
I was about to write some tests for the graphml stuff and noticed that `test_graph.py` would benefit a lot from more pytest fixtures. For example; `test_branching_evaluation_sequence`, `test_serialize_graph_to_json`, `test_serialize_graph_to_pickle`, `test_string_representations` could all use the same graph but the graph is built from scratch in every method.

Moving this graph creation to a fixture would allow for easy reusability.
I would also like to move fixtures used by multiple test files to a single file `conftest.py`.

Let me know what you think @PaulSchweizer @neuneck @Onandon11 .

**Comment by PaulSchweizer** [comment]
Good idea but we had some issues with conftest.py in the past, the story is unfolding here: https://github.com/PaulSchweizer/flowpipe/pull/55

That being said, now that we do no longer run the tests under py3.4-3.5 we should be good with the conftest.py

**Comment by Anton-4** [comment]
Alright, I will run a small test with conftest.py first to see if I don't break anything.
