### ISSUE TITLE
Add test instructions to contributor guide

### ISSUE THREAD

**Issue by Anton-4** [PaulSchweizer/flowpipe#110]
It would be useful to add instructions to run the tests to the contributors guide.
Especially because I also failed to run the tests :stuck_out_tongue: .

I tried the following:
```
python3.6 -m venv ./venv
source venv/bin/activate
pip install -r requirements.txt
pip install -r test-requirements.txt
python setup.py install
pytest ./tests
```

Which results in a lot of import errors similar to this one:
```
_________________________________________________________________ ERROR collecting tests/test_subgraphs.py __________________________________________________________________
ImportError while importing test module '/home/anton/gitrepos/flowpipe/tests/test_subgraphs.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_subgraphs.py:3: in <module>
    from flowpipe import Graph
E   ImportError: cannot import name 'Graph'
```

**Comment by PaulSchweizer** [comment]
Good idea, we should add some more info about the tests in there. 
The solution should be to use the develop flag when installing the setup.py:
`python setup.py develop`

**Comment by Anton-4** [comment]
Excellent, thank you. I will bundle the instructions with the conftest stuff from #109 .
