### ISSUE TITLE
Add a default value for raise_after in Graph.evaluate

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#112]
The flowpipe `Graph.evaluate(mode="threading")` hangs if any node with downstream dependencies throws an exception. This is remedied by setting `raise_after` to a finite value `n`, which will raise a `RuntimeError` if no threads are currently processing and no new threads have been spun up for `n` consecutive iterations of the evaluation loop. While small values of `raise_after` can cause premature breaking out of the loop just because the thread spawning overhead can be non-negligible, I think a large default value (100?) is preferable for the user experience than having the execution hang indefinitely.

Code to reproduce:
```
from flowpipe import Graph, Node

@Node(outputs=["out1"])
def OKNode(in1):
    return {"out1": 42}

@Node(outputs=["out2"])
def CrashNode(in2):
    raise Exception("I crashed!")
    return {"out2": 42}

ok_graph = Graph()
n1 = OKNode(graph=ok_graph, name="n1")
n2 = OKNode(graph=ok_graph, name="n2")
n1.outputs["out1"] >> n2.inputs["in1"]

hang_graph = Graph()
n3 = CrashNode(graph=hang_graph, name="n3")
n4 = OKNode(graph=hang_graph, name="n4")
n3.outputs["out2"] >> n4.inputs["in1"]

if __name__ == "__main__":
    print("Running ok_graph")
    ok_graph.evaluate(mode="threading", raise_after=None)
    print("Everything is ok!")

    print("Running hang_graph")
    hang_graph.evaluate(mode="threading", raise_after=None)
    print("The interpreter never gets here!")
```

**Comment by PaulSchweizer** [comment]
I see, maybe we can find a way to catch these exceptions to inform the "main" thread instead of relying on the time. I haven't looked into this possibility yet but I think it'd be worth researching
