### ISSUE TITLE
How do you unittest your node implementations?

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#113]
I find it tricky to write good tests for my nodes. This might be because I use them as thin wrappers around functionality that is tested elsewhere, so there's little things to actually hook into. Nevertheless, I would be very interested in how other people approach tests for their nodes.

**Comment by PaulSchweizer** [comment]
Good question. In your case I guess it does not make too much sense to write tests for the nodes themselves, it should be enough to test your actual implementations I guess.
For me, I test them like any other code, I can't think of anything special I'd do.

```python
def test_mynode():
    node = MyNode(input1="something")
    node.evaluate()
    assert node.outputs["out"].value == "expected output"
```
