### ISSUE TITLE
Data persistence causes memory to grow

### ISSUE THREAD

**Issue by Onandon11** [PaulSchweizer/flowpipe#114]
After a fair amount of flowpipe usage I recognize a significant grow in memory usage. Our project mainly uses `np.ndarray`, these arrays can grow as large of 1200 million floats. The usage of `INode` causes that the variables keep a reference count larger than zero. Therefore the garbage-collector won't remove these variables and keep them in memory. I would like to keep only the input data and the output data of the graph, not all of the individual variables in between (unless they are referenced outside `flowpipe` ofcourse). 

My idea was to create a `DATA_PERSITANCE` flag or suchlike. Which a user can toggle if they need to debug the code. Otherwise there is no need to keep storing all of the individual input and output data.

**Comment by neuneck** [comment]
Hi,

To my use case, keeping the intermediate Input and Output Plug values is
crucial.

We could add a flag to nodes that runs a 'del' on its input and output plug
values after the node sets itself clean. That could get done what you need,
I guess.

**Comment by PaulSchweizer** [comment]
Sounds like a plan, we can `del` after having pushed to the downstream plugs and we control it by an env var and/or an input arg passed to evaluation. I can take a look at this next year after the holidays, but if anyone of you wants to take a look at it in the meantime, feel free to do so
