### ISSUE TITLE
Revamp multiprocessing in the same manner as multithreading

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#120]
It is in principle possible, to use the same framework (concurrent.futures) to do both, multithreading and multiprocessing. The use of that high-level API is, of course, that a lot of the edge cases are handled neatly and the overall stability is great.

A trade-off with the concurrent.futures.ProcessPoolExecutor is that it can only handle picklable objects (cf. https://docs.python.org/3.7/library/concurrent.futures.html#processpoolexecutor).
If that is a limitation we could live with, I'm ready to have a go at revamping the multiprocessing evaluation of a graph.

So
* do we want to use the ProcessPoolExecutor at all?
* is the limitation to picklable objects acceptable for the current use cases of this API?

**Comment by PaulSchweizer** [comment]
Ok, good idea. 
Maye we should think about introducing some sort of a "GraphRunner" design. A base class that evaluates the graph "in some way". We could then have a "FuturesMultiprocessingRunner" and a "LegacyMultiprocessingRunner" (as well as the linear and multithreading one). That way we could keep both options.
This would also open a gateway to entirely different evaluation methodologies, for example evaluating a Graph via celery or custom networks. I've done that in the past but having a built-in hook for these situations would be beneficial.
It's just a rough idea at the moment, so I hope you know what I mean?

**Comment by neuneck** [comment]
Yes that sounds like a great idea! 
I will be super busy for the next few weeks, though, as we are in a hard crunch phase right now, but if nobody else takes this on in the meanwhile, I'll gladly take care of it.

**Comment by PaulSchweizer** [comment]
Nice, I'll assign this to you then, once you're ready let me know.
