### ISSUE TITLE
Is the release documentation out of date?

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#123]
I recently revamped the threading evaluation, which we use heavily, and fixed a bug. Now I wanted to release that, but it seems the release documentation[ in our contributing guide](https://github.com/PaulSchweizer/flowpipe/blob/master/contributing.md) is not entirely up to date.
There, the steps (as far as I understand are):
1. change the version number in `flowpipe/__init__.py` and commit that to master
2. draft a new release, setting the same version number as the release tag
3. click on the "Publish Release" button.

Now, the `__init__.py` does not have a version number string. Instead, the `setup.py` defines the version number for the package. So are the appropriate steps now
1. change the version number in `setup.py` and commit that to master
2. draft a new release, setting the same version number as the release tag
3. click on the "Publish Relase" button.
?

Since I am unsure and don't want to break things, I am holding back on just trying that out, and will wait for clarification. @PaulSchweizer what's the right way to go about things? Once the procedure has been clarified I will gladly update the contributor's guide.

**Comment by PaulSchweizer** [comment]
Sorry, yes, the second approach is the correct one, change the version in setup.py. The version in init caused issues since we added the import for the classes (Node, Graph etc.) to the init.

**Comment by neuneck** [comment]
My release was successful and the documentation is updated!
