### ISSUE TITLE
Node and Graph equality checks

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#145]
**Is your feature request related to a problem? Please describe.**
When writing tests involving flowpipe objects, it can be very useful to be able to compare nodes and graphs. I just now found myself constructing equality checks for Graphs and Nodes and think this might be a useful feature.

**Describe the solution you'd like**
Graph, Node and IPlug should support the `__eq__(self, other)` magic method.

**Describe alternatives you've considered**
Building custom code to check for graph/node equality can yield patchy results, and might be hard to do for inexperienced users, as this involves a good understanding of the relationships of various flowpipe objects.

**Additional context**
I deem two graphs to be equivalent if they contain the same nodes and all the nodes in the two graphs are equivalent.
I deem two nodes to be equivalent if they have
* the same upstream nodes (by `Node.name`, not instance), the same input plug names and values,
* the same Input and Output Plugs
* the same `is_dirty` status
I deem two Plugs to be equivalent if they have
* the same name
* the same connections (by name)
* the same value.

I think with these conditions should make it possible to effectively judge if two flowpipe graphs are the same (and in the same state). 
What do you think? Would that be a useful definition of equivalence between flowpipe objects for your work?

**Comment by PaulSchweizer** [comment]
Sounds reasonable. Are there any further updates on this from your side, otherwise I'd look into this

**Comment by neuneck** [comment]
Please go ahead. What I hacked for our unit tests is

```
def node_eq(node1, node2):
    same = True

    up1 = {n.name for n in node1.upstream_nodes}
    up2 = {n.name for n in node2.upstream_nodes}
    if up1 != up2:
        same = False

    in1 = {in_name: in_.value for in_name, in_ in node1.inputs.items()}
    in2 = {in_name: in_.value for in_name, in_ in node2.inputs.items()}
    if in1 != in2:
        same = False

    out1 = {in_name: in_.value for in_name, in_ in node1.outputs.items()}
    out2 = {in_name: in_.value for in_name, in_ in node2.outputs.items()}
    if out1 != out2:
        same = False

    if node1.is_dirty != node2.is_dirty:
        same = False

    return same


def graph_eq(graph1, graph2):
    same = True

    g_nodes = {n.name for n in graph1.all_nodes}
    g_rec_nodes = {n.name for n in graph2.all_nodes}
    if g_nodes != g_rec_nodes:
        same = False

    def get_node(g, n):
        for node in g.all_nodes:
            if node.name == n:
                return node
        else:
            raise KeyError(f"No node named {n} in the graph")

    if same:  # make sure not to run into errors if other nodes are present
        for node_name in g_nodes:
            node1 = get_node(graph1, node_name)
            node2 = get_node(graph2, node_name)
            if not node_eq(node1, node2):
                same = False

    return same

```

**Comment by neuneck** [comment]
@PaulSchweizer Did you make any progress here? Otherwise, I could add these equivalence checks to the codebase quite easily.

**Comment by PaulSchweizer** [comment]
Sorry, I started working on this, but then got completely sidetracked. Please feel free to implement it, if it is easy for you!
I pushed my state to: https://github.com/PaulSchweizer/flowpipe/tree/145-wip-node-equality
Maybe it helps, but if not, feel free to start from scratch!

**Comment by neuneck** [comment]
This turns out to be significantly more complicated than I had anticipated. So far, I never needed any object for which I defined `__eq__()` to be a hashable collection. Obvious choices for building a custom hash didn't work out, so I guess I'm stuck at the very same point as you.
I don't see a clear path forward and deem the feature a "nice to have", so I would be okay with closing this issue as a "won't implement (at the moment)". What do you say, @PaulSchweizer ?

**Comment by PaulSchweizer** [comment]
Agreed!
