### ISSUE TITLE
Do we want to apply black code styling?

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#156]
I recently was pointed towards the [black](https://github.com/psf/black) code styling tool, and like the idea of adhering to a fixed code style.

It's a tool with very little configuration (ideally none) that automatically structures python code. The big advantage here is that it's an uncompromising code style that's applied automatically. Thus is guarantees consistent code style across any number of authors, regardless of an author's experience in styling code. By being a tool that produces consistent output, less heed has to be payed to the code style while coding.

What do other contributors think?

**Comment by PaulSchweizer** [comment]
Yes! That was on my invisible todo list anyways. Best to also combine it with isort and and also put it in a pre-commit hook.

**Comment by neuneck** [comment]
Closed by #158
