### ISSUE TITLE
Travis integration seems broken

### ISSUE THREAD

**Issue by PaulSchweizer** [PaulSchweizer/flowpipe#160]
Travis and other integrations we use don't seem to work anymore. Investigate why.

- [x] Can this be done with github pipelines? I've never used them, so I'm not sure what they're capable of or made for
- [x] Check codacy
- [x] pylint check
- [x] Tests and coverage
- [x] publishing pipeline

**Comment by PaulSchweizer** [comment]
travis is no longer free, so we gotta look into github pipelines.

**Comment by neuneck** [comment]
I've only ever been a user of CI/CD pipelines, modifying existing templates to work with various repos. Still, if you do need / want help on something here, I can try to chime in. Just let me know what I can do without interfering with your own work on this.

**Comment by PaulSchweizer** [comment]
Thanks @neuneck I was thinking about creating actions for:
- linting, blocking PRs from getting merged if it fails
- tests, if possible for py2.7 (unfortunately this is still required for my use case) and py3.7+, also blocking PRs if they fail
- deployment to PyPi when updating the main branch. Not sure how to handle the version tag. Maybe only if the version has changed as well?
There seem to be templates for most those actions already. If you have experience with any of those actions, feel free to contribute. I was planning to tinker with this sometime in the coming week
