### ISSUE TITLE
evaluation_matrix performance improvement

### ISSUE THREAD

**Issue by DaveMtl** [PaulSchweizer/flowpipe#169]
Greetings,

I'm not certain if this information remains pertinent with the latest version of the library, but I wanted to share it just in case it might be helpful.

We are using an older version of the library and encountered significant performance issues with the evaluation_matrix function when evaluating complex graphs (comprising 47 modules with connections all over the place).

As it turns out, the recursive function inside evaluation_matrix was called no less than 40 million times to determine the processing order. So we changed it for the following function and now it's called 144 times only. Needless to say, this represents a significant improvement. I noticed that you modified the way it's handled in the latest version, so I'm unsure if this information is still applicable. Nevertheless, here is the function, just in case it proves useful.

```
@property
    def evaluation_matrix(self):
        """Sort nodes into a 2D matrix based on their dependency.
        Rows affect each other and have to be evaluated in sequence.
        The Nodes on each row however can be evaluated in parallel as
        they are independent of each other.
        The amount of Nodes in each row can vary.

        Returns:
            (list of list of INode): Each sub list represents a row.
        """
        root_nodes = []

        # Find root nodes
        for node in self.all_nodes:
            if len(node.upstream_nodes) == 0:
                root_nodes.append(node)

        # Inline recursive function to parse the tree of nodes and assign
        # the order at which they are safe to be executed based on their relation
        # to their parent's order.
        def recursive_set_order(node, order):
            node.order = order
            # For each output
            for key, outputPlug in node.outputs.items():
                # For each connection
                for connection in outputPlug.connections:
                    # if output.order is not defined yet or lower than it now needs to be,
                    # call the recursive function to change it and change its children.
                    if not hasattr(connection.node, "order") or \
                        connection.node.order < order + 1:
                        recursive_set_order(connection.node, order + 1)

        # For each root nodes
        for node in root_nodes:
            order = 0
            recursive_set_order(node, order)

        levels = {}
        for node in self.all_nodes:
            levels[node] = node.order
```

**Comment by PaulSchweizer** [comment]
Hi @DaveMtl thanks for pointing this out, this issue has already be fixed a while ago actually. Please try updating to the latest version. Let me know if you need any help or further information

**Comment by PaulSchweizer** [comment]
Closing this, but please let me know if this is still an issue
