### ISSUE TITLE
Move docs to sphinx

### ISSUE THREAD

**Issue by PaulSchweizer** [PaulSchweizer/flowpipe#17]

**Comment by PaulSchweizer** [comment]
https://github.com/davidstutz/sphinx-example

**Comment by PaulSchweizer** [comment]
I started setting this up here: https://github.com/PaulSchweizer/flowpipe/tree/sphinx-docs
But this is just me dabbling with it and trying to figure out what we'd need.
Here's the doc: https://flowpipe.readthedocs.io/en/sphinx-docs/
Feel free to join the dabbling @Onandon11.

**Comment by Onandon11** [comment]
I have no experience with creating Sphinx docs, I will study it a bit and join the doc development :)

**Comment by PaulSchweizer** [comment]
I am almost there, I just can't get the autodoc to work on readthedocs (or locally), the docs look like this at the moment: https://flowpipe.readthedocs.io/en/sphinx-docs/

Am I missing anything, does someone know how sphinx autodoc has to be set up, I am at a loss.
