### ISSUE TITLE
replace imp with importlib

### ISSUE THREAD

**Issue by PaulSchweizer** [PaulSchweizer/flowpipe#47]
imp is deprecated since 3.4, should be replaced.
Used in node.py and utilities.py
Basically making this part look a bit nicer while still maintaining backwards compatibility (py2.6)

**Comment by neuneck** [comment]
Attempted solution in https://github.com/PaulSchweizer/flowpipe/pull/121

**Comment by PaulSchweizer** [comment]
Closing, thanks @neuneck  for the implementation
