### ISSUE TITLE
Is concurrent execution of the graph possible or planned?

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#48]
Hi Paul,

I am looking for a flow based execution library to orchestrate a flow through a set of Microservices. Your work seems compelling!
My individual nodes would consist of REST calls that can, in part, run concurrently. I have seen that your graph already support layering nodes into parallelizable layers. I did not see an option to execute the graph concurrently.

As the execution matrix is available already, are there plans to add concurrency to the project? Is that functionality already available, maybe?

In any case, awesome work, I learned something just reading the code!

Cheers, Julian

**Comment by PaulSchweizer** [comment]
Hi Julian, 

Thanks for the comments and your interest!

Currently, there are no plans to add such an execution framework. Mostly because in my use cases, there is already a system that handles parallel execution for me and I am simply converting the flowpipe graphs into something that that system can understand. So I simply had no need for this yet.

But that being said, it would be really cool to have such a parallel execution system. I will give this some thought to see how easily this could be achieved. But feel free to look into this as well, contributions are always very welcome!

**Comment by neuneck** [comment]
Hi Paul,

I looked into concurrency with asyncio a little. I'm afraid adding that to flowpipe directly would basically imply duplicating the entire codebase. functions and coroutines are not interoperable at all. If you come to a different conclusion I would love to discuss what options you see. 

For the time being, in order not to clutter any package (and because I would like to go differently about serialization), I will probably implement my own flow-based computation package.

Again, thank you for this neat and pythonic implementation. I will definitely draw inspiration from it!

Best, Julian

**Comment by PaulSchweizer** [comment]
Hi Julian, 

Thanks for the investigations on your part, I haven't really looked into asyncio so far, but from what I read, it seems your findings are correct, we would need to restructure this library quite a bit.

But, I whipped up this surprisingly simple threading solution, actually surprised me how simple it was (could still be improved of course):

```python
"""
+---------------+          +---------------+
|   Sleeper1    |          |   Sleeper2    |
|---------------|          |---------------|
o in1<>         |     +--->o in1<>         |
|           out o-----+    |           out o
+---------------+     |    +---------------+
                      |    +---------------+
                      |    |   Sleeper3    |
                      |    |---------------|
                      +--->o in1<>         |
                      |    |           out o
                      |    +---------------+
                      |    +---------------+
                      |    |   Sleeper4    |
                      |    |---------------|
                      +--->o in1<>         |
                           |           out o
                           +---------------+
"""
import threading
import time

from flowpipe.node import Node
from flowpipe.graph import Graph


@Node(outputs=["out"])
def Sleeper(in1):
    time.sleep(1)


def g():
    graph = Graph(name='Threading')
    sleep1 = Sleeper(graph=graph, name='Sleeper1')
    sleep2 = Sleeper(graph=graph, name='Sleeper2')
    sleep3 = Sleeper(graph=graph, name='Sleeper3')
    sleep4 = Sleeper(graph=graph, name='Sleeper4')
    sleep1.outputs['out'].connect(sleep2.inputs['in1'])
    sleep1.outputs['out'].connect(sleep3.inputs['in1'])
    sleep1.outputs['out'].connect(sleep4.inputs['in1'])
    return graph


def evaluate_threaded(graph):
    threads = {}
    nodes = [n for n in graph.evaluation_sequence]
    while not all([not n.is_dirty for n in nodes]):
        for node in nodes[:]:
            if not node.is_dirty:
                nodes.remove(node)
                continue
            if node.name not in threads and all([not n.is_dirty for n in node.upstream_nodes]):
                threads[node.name] = threading.Thread(target=node.evaluate)
                threads[node.name].start()
                

b = time.time()
g().evaluate()
print "SEQUENTIAL:", time.time() - b

b = time.time()
evaluate_threaded(g())
print "THREADED:", time.time() - b

# Output:
# SEQUENTIAL: 4.00400018692
# THREADED: 2.01399993896
```

Maybe that helps? 

Also I'd like to know what you'd do differently in terms of serialization? I was thinking of simplifying it at some point, just haven't put any thoughts into it yet, so if you have suggestions, let me know. Also, if you move forward with your own implementation, let me know where I can find it if possible!

**Comment by neuneck** [comment]
Hi Paul,

first of all: Great work on that threading solution. It looks easy enough to add it. My guess would be that since each node is run in it's own thread, a user wouldn't have to care about thread safety of his calls a lot - unless she uses shared resources. And that's exactly what I will do: I want to use a flow-based approach to orchestrate a bunch of stateless microservices that partially depend on each other's outputs.

I am not familiar with introspection, so I can't tell how robust the `import_class` function is across environments. Does it assume the files to be in consistent locations or is it enough to have them somewhere in pythons import search path? To me it seems easier to require the user to supply a well-defined graph and then load that graph's state. Since your approach is quite sophisticated I assume it is an important feature for your workflow. 

Also, my serialization use case is much simpler than what you built. I want to re-use node/plug values between different instantiations. As such, I can assume the same graph structure is set up by user code every time. Thus, I don't need to build a serialized structure that allows me to import and re-build the graph itself, but would just use regular pickling to serialize a dictionary mapping node / plug ids to pickleable value objects.

Best, Julian

**Comment by PaulSchweizer** [comment]
Yes, thread safety is guaranteed as long as the user does not use shared objects as you mention. Is that what you want to do? Use shared objects of some sort?
Maybe you could sketch out a rough outline of what your graph would look like, I don't fully understand your intendend workflow tbh.
Serialization: I see, you just want to apply values to an existing graph, yes, that would require a new function, but would still be possible with flowpipe, like read data and just iterate over the existing graph and apply the values.

**Comment by neuneck** [comment]
As I mentioned very briefly, I want to orchestrate several microservices. The runtimes of these services can range from 0.5 to 10 seconds. I need to wait on the inputs becoming available in a database and then kick off calls to the services, as soon as all their dependencies are met, since in my scenario the user is actively waiting on the final result of the process. I set up a somewhat simplified version of the flow and attached the ascii version that flowpipe generates - it's not perfect, but it should be illustrative enough.

In case the result is not satisfactory, the user might supply different inputs and wait for the updated result. Hence, in that scenario I need to make sure only to run the steps that depend on the updated inputs. 

After re-reading some of the code base and getting a more thorough understand of how flowpipe works, I think your threaded solution might actually fit my use case. My previous concern was based in a misconception on how results are handed along the graph.

[flow.txt](https://github.com/PaulSchweizer/flowpipe/files/3438474/flow.txt)

P.S.:
In parallel, I did some further reading on asyncio. I think there might be a neat way to use queues connecting output and input plugs along with changing the `compute` method  on nodes to accept both functions and coroutines to make concurrency available without changing the API. I will play around with that a little and tell you if I get something neat out of it.

**Comment by PaulSchweizer** [comment]
Thanks for the mockup, it makes more sense to me now. 
I'm really excited to see what comes of this, would be cool if we could make this work! Let me know if you need anything in the meantime

**Comment by neuneck** [comment]
I will spend some time this week extending your threading suggestion into something that can be pulled into master. Since I did not find any contribution guidelines, did you settle on a documentation standard or other code guidelines? I aim to make integration of my PR as little work as possible :)

**Comment by PaulSchweizer** [comment]
Great, thanks @neuneck ! 
True, I should put up some guidelines for contributing. 
These are the standards I myself try to abide to: 
- pep8 standard 
- keep it backwards compatible (there are some folks inclusing myself who still run it a py 2.7 environment for at least another half a year, sorry ...). If that's not possible, we can still put it in but should somehow exclude that code from older python versions, like with a try/except or something.
- achiving 100% code coverage, meaning, explicitely stating what is excluded in the [.coveragerc](https://github.com/PaulSchweizer/flowpipe/blob/master/.coveragerc) file. I think we dropped to 98 recently, it should be an easy fix to get back to 100, maybe you could do that in that go as well (only if you want to though)?
- documentation standard would be the google one: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html Currently I'm building doxygen docs https://paulschweizer.github.io/flowpipe/ but would like to switch to sphinx one day.

**Comment by neuneck** [comment]
Closing this issue because a PR based on @PaulSchweizer 's suggestion on threaded evaluation has been issued.
