### ISSUE TITLE
Add a global default graph

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#53]
I work with tensorflow on a regular basis, which also has a graph-based evaluation scheme. There, a default global graph exists and nodes not specifically assigned to a different graph will be added to that.

The main advantage is that the API becomes simpler for the - ostensibly standard - use case of having a single graph to evaluate. No graph needs to be instantiated and managed by users.

The main disadvantage is, of course, that it's less explicit, which might lead to user confusion. 

I think it would be an easy addition, making flowpipe easier to use. It could be implemented with acceptable effort and without backwards incompatibility. Before moving forward on this, I would like to get your opinion on the proposal.

**Comment by PaulSchweizer** [comment]
Thanks for the idea, I think that would be a good feature to add and definitely save some time! 

- Can the default graph be reset/cleared?
- Where would it be, in graph.py?
- Do we need more utilities for this?

I imagine it to look something like this, but please correct me if I'm wrong:

```python 
from flowpipe.node import Node 
from flowpipe.graph import DefaultGraph

@Node()
def MyNode():
    pass

my_node = MyNode()  # No graph specified

print(DefaultGraph)

```

Output
```
+----------+
|  MyNode  |
+----------+
+----------+
```

**Comment by neuneck** [comment]
I had something super simple in mind. In the flowpipe `__init__`
```python
import logging
from .graph import Graph  # with backwards-compatible handling of relative imports
...
default_graph = Graph(name='default')

def get_default_graph():
  return default_graph

def set_default_graph(graph):
  global default_graph
  default_graph = graph
```
And in node.py
```python
...
from . import default_graph
...
class INode(object):
    __metaclass__ = ABCMeta
    def __init__(self, name=None, identifier=None, metadata=None, graph=default_graph):
...
```

My rationale for putting it into the `__init__.py` is that is a module-level concept and thus should be accessible as `flowpipe.get_default_graph()`.

**Comment by PaulSchweizer** [comment]
Sounds good, only thing I'd add is a "clear/reset" functionality which would be useful for interactive sessions, something like this:

```python
def reset_default_graph():
    global default_graph
    default_graph = Graph(name='default')
```

And another question that just came to mind: Are we going to get import loops from this as graph is currently importing node.INode?

**Comment by neuneck** [comment]
Indeed. With a minor refactor, that could be amended, though. The only function from the INode that is ever used in a graph is the staticmethod `INode.deserialize`.

My suggestion would be to refactor the static deserialize methods into a new module, `deserialize.py` and wrap calls to the functions there to maintain backwards compatibility.

**Comment by PaulSchweizer** [comment]
Sounds good, @Anton-4 also started working on this ticket, serializing the graph to graphml, https://github.com/PaulSchweizer/flowpipe/issues/32
So in the long run it might make sense to continue down that road and introduce a "serialization.py" that can then contain different serializers as started here: https://github.com/Anton-4/flowpipe/commit/7ad87742cea8a41c0fb2fa43314fc70e6901f6f6

But this being said, this should be a separate issue and we should not conflate these two, so let's go with the utilities.py approach you mentioned for now, we can come back later and refactor this accordingly
