### ISSUE TITLE
The first example in README.md is broken

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#57]
I think the example in the README needs to import InputPlug and OutputPlug to work as copy/paste code.

Also, the dict values in the party node needs to be converted to list explicitly to allow for slicing:
```python
@Node()
def Party(attendees):
    print('{0} and {1} are having a great party!'.format(
        ', '.join(list(attendees.values())[:-1]), list(attendees.values())[-1]))
```

**Comment by PaulSchweizer** [comment]
Thanks for catching this, I think the best future proof solution will be to also set up a test for the readme file, should be doable through eval'ing everything inside a python block in the readme.md.

**Comment by PaulSchweizer** [comment]
Thanks for fixing it right away, the test idea is not urgent but I may come back to it and integrate it at some point cause it's always a pain having to manually test examples and then finding out that they are actually broken
