### ISSUE TITLE
RuntimeError: Could not sucessfully compute all nodes in the graph Test

### ISSUE THREAD

**Issue by Onandon11** [PaulSchweizer/flowpipe#64]
I'm trying to use the code for geometrical dataprocessing. This data can be huge and contain millions of point and multiple processing steps. Therefore I want to use multi-threading (better should be multi-processing), but I get an error which I can't place what's wrong.

I'm running Python 3.6.5 and the latest code from you repo. Code to reproduce:

```
import time
import logging

import numpy as np
from flowpipe.graph import Graph
from flowpipe.node import Node
from flowpipe import logger


@Node(outputs=['vec'])
def getData(file):
    return {'vec': np.random.rand(100,3)}

@Node(outputs=['mean'])
def getMean(vec):
    return {'mean': vec.mean(axis=0)}

@Node(outputs=['vec'])
def setZero(vec, mean):
    return {'vec': vec - mean}

@Node()
def prettyPrinter(vec):
    print(vec.mean(axis=0))

def process_flowpipe():
    start = time.time()

    graph = Graph(name='Test')

    getdata = getData(graph=graph, name='Get Data', file=r'C:\testfile')
    getmean = getMean(graph=graph, name='Get Mean of data')
    setzero = setZero(graph=graph, name='Set data to zero')
    printer = prettyPrinter(graph=graph, name='I print pretty')

    getdata.outputs['vec']  >> getmean.inputs['vec']
    getdata.outputs['vec']  >> setzero.inputs['vec']
    getmean.outputs['mean'] >> setzero.inputs['mean']
    setzero.outputs['vec']  >> printer.inputs['vec']
    
    print(graph.name)
    print(graph)
    print(graph.list_repr())

    logger.setLevel(logging.DEBUG)
    
    # graph.evaluate(threaded=False)
    graph.evaluate(threaded=True)

if __name__ == "__main__":
    process_flowpipe()

```

**Comment by PaulSchweizer** [comment]
Thanks for the report again and the detailed example, very much appreciated!

I created a PR with changes that fixed this issue for me: https://github.com/PaulSchweizer/flowpipe/pull/65

Could you give it a go in your local environment?

Aside from that multi-processing is indeed something I'd like to have as well. If you have any further ideas or requirements that you would want to share in that regard I'd be very happy for the input (feel free to raise a ticket for it)

**Comment by Onandon11** [comment]
Thank you for your quick response :)

The reason why I have some questions and found some bugs is due to the fact that we want to use your module for our own project. We currently have a similar module but is much less mature than yours. I stumbled upon your module because we were searching for a standard module, or at least a module which is used by more people than only use, for Flow Based Programming in Python.

**Comment by PaulSchweizer** [comment]
Cool, I'm happy you're trying out flowpipe! I am actively using it myself, although in a different environment than you so I'm sure that there will be a few more issues surfacing when you use it more. So if you have any input, don't hesitate to share it!

**Comment by Onandon11** [comment]
[](url)
