### ISSUE TITLE
ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by Onandon11** [PaulSchweizer/flowpipe#68]
When returning numpy arrays which are not C-contiguous an error is raised at the `sha256(o).hexdigest` row.

Can we check for numpy array and the make the array c-contiguous. At row 59 in `flowpipe\utilities.py`. Like the following:
```
class NodeEncoder(JSONEncoder):
    """Custom JSONEncoder to handle non-json serializable node values.

    If the value is not json serializable, a sha256 hash of its bytes is
    encoded instead.
    """

    def default(self, o):
        """Encode the object, handling type errors by encoding into sha256."""
        try:
            return super(NodeEncoder, self).default(o)
        except TypeError:
            if isinstance(o, np.ndarray): # <------------ THIS :D
                o = np.ascontiguousarray(o)
            try:
                return sha256(o).hexdigest()
            except TypeError:
                return str(o)
```

PS.: Maybe you can give me the rights to make branches and help you develop?

**Comment by Onandon11** [comment]
You can repoduce the exception with the following code:

```

from flowpipe.node import Node
from flowpipe.graph import Graph
import numpy as np

@Node(outputs=['a'])
def foo(b):
    return {'a': np.arange(10)[::2]} 

graph = Graph(name='Exception C-continguous')
foo1 = foo(graph=graph, name='Test', b=1)
foo2 = foo(graph=graph, name='Test 2')

foo1.outputs['a'] >> foo2.inputs['b']
graph.evaluate()
```

**Comment by neuneck** [comment]
I would much prefer to add a second `except` clause to the `try` statement, catching `ValueError` and resorting to `bytes(o)` in those instances. My reasoning is as follows:

1. It does not add a dependency to a rather large library just for an edge case sanitization.
2. It will actually catch more cases.
3. Explicitly type-checking here does not strike me as particularly pythonic.

I already prepared a simple fix and issued a PR, cf. https://github.com/PaulSchweizer/flowpipe/pull/69

It would be great if you, @Onandon11 , could check if that fixes your issue.

**Comment by neuneck** [comment]
@Onandon11 The easiest way to contribute would be to 

- fork flowpipe yourself
- work on a branch in your own fork of the repo
- submit a pullrequest against this repo

If you need further guidance on how to do so, I'm happy to go into more detail :-)

**Comment by Onandon11** [comment]
> I would much prefer to add a second `except` clause to the `try` statement, catching `ValueError` and resorting to `bytes(o)` in those instances. My reasoning is as follows:
> 
> 1. It does not add a dependency to a rather large library just for an edge case sanitization.
> 2. It will actually catch more cases.
> 3. Explicitly type-checking here does not strike me as particularly pythonic.
> 
> I already prepared a simple fix and issued a PR, cf. #69
> 
> It would be great if you, @Onandon11 , could check if that fixes your issue.

**Comment by Onandon11** [comment]
I agree adding the numpy dependency to the module is nog the best idea. Sorry I was projecting my own use-cases to much at the flowpipe module :) I use flowpipe for dataprocessing and therefore have heavy dependencies with numpy and scipy.

I agree with adding another except statement is much better 👍 .

I will try your approach, I will let you know when I have any questions. Maybe I will try to make a test PR, if that's ok..
