### ISSUE TITLE
Add a `get_node` or `__getitem__` method to Graph in order to get nodes by name

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#70]
It would be convenient to have a `get_node` method on the Graph class to be able to retreive nodes by name. This plays well together with the fact that nodes in the graph have to have unique names.

This is easy enough to implement for cases where it doesn't work, but I have a hard time figuring out what the proper behavior should be in case a node of the given name does not exist. 

An alternative would be to implement the `__getitem__` magic, where a missing key would be handled with a KeyError.

What do you guys think?

**Comment by PaulSchweizer** [comment]
@neuneck , this is already available via `__getitem__`, exactly the way you describe it : https://github.com/PaulSchweizer/flowpipe/blob/master/flowpipe/graph.py#L37

Maybe this should be mentioned in the README somewhere
