### ISSUE TITLE
No function to guess the number of SubOutputPlugs

### ISSUE THREAD

**Issue by Onandon11** [PaulSchweizer/flowpipe#72]
I have a function which makes a number of suboutputplugs. But before runtime I don't know how many. How can I connect all the outputs without knowing the number at forehand.. any ideas?

**Comment by PaulSchweizer** [comment]
@Onandon11 you'd somehow need to know the number of (sub)outputs before graph evaluation, otherwise you can't construct the graph, right? Or maybe I am misunderstanding the question or you have a specific scenario in mind?

Does this example help:

```python

from flowpipe.graph import Graph
from flowpipe.node import Node


@Node(outputs=['out'])
def Generate(count):
    return {str(i): i for i in range(count)}


@Node()
def MyPrint(value):
    print(value)


count = 3
graph = Graph()
generate = Generate(graph=graph, count=count)

for i in range(count):
    p = MyPrint(graph=graph, name="MyPrint" + str(i))
    generate.outputs['out'][str(i)] >> p.inputs['value']


print(graph)

```

The graph:

```
+--------------------+          +---------------+
|      Generate      |          |   MyPrint0    |
|--------------------|          |---------------|
o count<3>           |     +--->o value<>       |
|                out %     |    +---------------+
|             out.0  o-----+    +---------------+
|             out.1  o-----+    |   MyPrint1    |
|             out.2  o-----|    |---------------|
+--------------------+     +--->o value<>       |
                           |    +---------------+
                           |    +---------------+
                           |    |   MyPrint2    |
                           |    |---------------|
                           +--->o value<>       |
                                +---------------+
```

**Comment by Onandon11** [comment]
@PaulSchweizer, you are right! Without knowing the number of suboutputplugs there is no way to connect the plugs to subsequent nodes. 

You example helps indeed! But without knowing the value for count... So more like this:
```python
from flowpipe.graph import Graph
from flowpipe.node import Node


@Node(outputs=['out'])
def Generate():
    return {str(i): i for i in range(3)}


@Node()
def MyPrint(value):
    print(value)


graph = Graph()
generate = Generate(graph=graph)

# So what from here? You don't know the number of outputs from the Generate Node. 
#The value for count is unknown...
count = ???
for i in range(count):
    p = MyPrint(graph=graph, name="MyPrint" + str(i))
    generate.outputs['out'][str(i)] >> p.inputs['value']


print(graph)
```


Maybe we need something like the following. Which maps all outputplugs automagically to the next nodes. Making as many connections as needed (at evaluation time).
```python
generate.outputs['out'].map >> p.inputs['value']
```

**Comment by PaulSchweizer** [comment]
I think I know what you mean now.
Basically, your graph would look like this:

```
+---------------+          +--------------+
|   Generate    |          |   MyPrint    |
|---------------|          |--------------|
|           out o--------->o value<>      |
+---------------+          +--------------+
```

And after evaluation it would look like this:

```
+--------------------+          +----------------------+
|      Generate      |          |       MyPrint        |
|--------------------|          |----------------------|
|                out %--------->o value<{"1": 1, ">    |
|             out.0  o          +----------------------+
|             out.1  o
|             out.2  o
+--------------------+
```

The code would look like this:

```python
graph = Graph()
generate = Generate(graph=graph)
my_print = MyPrint(graph=graph)

generate.outputs['out'] >> my_print.inputs['value']
```

Now the problem currently is that `my_print` would not receive the values from `generate`. This was deliberate at the time but I think that we should change it. SubOutputPlugs have to inform their parent when their value changes.

**Comment by PaulSchweizer** [comment]
@Onandon11 , I created a PR that should solve your problem, but let me know if this is not what you meant

**Comment by Onandon11** [comment]
@PaulSchweizer, this is great, this indeed what I were looking for. 

Does the `my_print` node automatically sees that there are subnodes? And do the keys of the output of `my_print` node correspond to the names created in `generate`? 

Maybe I can make some sort of docstrings? I'm sometimes missing somewhat of the logic behind the whole structure.

FYI, we are currently working with your module on a day-to-day basis and so far it's great! Thanks for your quick reponse and support so far.

**Comment by PaulSchweizer** [comment]
Glad that this was the issue, let' try to explain how it works:

If an output plug, that produces sub-plugs, is directly connected to an input plug like this:

```python
generate.outputs['out'] >> my_print.inputs['value']
```

the downstream node will receive a dictionary with the sub plugs as keys and their values as values, so from our example above `my_print.inputs['value']` would hold these values:

```python
{'0': 0, '1': 1, '2': 2}
```

I hope that makes sense?

I have put this in the tests, but we should definitely put this more explanatory info somewhere else as well, docstring seems to be a good idea (I also want to move the docs to sphinx and host them on readthedocs, but haven't made too much progress so far as I have never gone through the whole procedure myself: https://github.com/PaulSchweizer/flowpipe/issues/17)

I'm happy to hear that you guys find flowpipe useful and thanks for the great input and contributions from you, very much appreciated!

**Comment by Onandon11** [comment]
Alright, that's indeed how I hoped it worked. This is great for automatic iteration over and outputplug which contains subplugs. 

I saw the tests indeed, however I don't have python at hand now and the actual logic behind was a bit unclear to me ..

Agree, Sphinx is the right place for such an extensive documentation. However I also haven't done the procedure myself. But I'm always eager to contibute, by writing documentation. Maybe we just give it a call and make a start?

**Comment by PaulSchweizer** [comment]
v0.5.4 is released with these changes.

**Comment by Onandon11** [comment]
> v0.5.4 is released with these changes.

Great, I updated the requirements.txt for our own repo :)
