### ISSUE TITLE
Can deserialize_node support customized subclasses of INode?

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#78]
When using the default deserialization, I keep running into trouble with my nodes. I subclass `INode` directly and don't see how/where the node properties / init parameters are (de)serialized. 

I am not sure how this can be remedied. Can one track with which parameters the `__init__` was originally called and store those internally for the serialization?

To reproduce:
```
from flowpipe.node import INode
from flowpipe.plug import InputPlug, OutputPlug

class MyNode(INode):

    def __init__(self, foo, **kwargs):
        super(MyNode, self).__init__(**kwargs)
        self.foo = foo
        InputPlug("input", self)
        OutputPlug("output", self)

    def compute(self, input):
        return {"output": "some output"}


ser = MyNode("bar").serialize()

deser = INode.deserialize(ser)
```

If I make the intialization parameter optional (de)serialization works, but the parameter I set does not get restored. This might be done by also serializing non-standard entries in an `INode`'s `__dict__` upon serialization, but then again that seems prone to a ton of runtime errors.

In the end, if this is not possible with a somewhat straightforward extension of the current serialization routines, I will set up something custom. My situation might be a bit special since I can recreate the original graph before deserialization, so I only need to track values in the plugs and not the entire structure.

**Comment by PaulSchweizer** [comment]
What about turning `foo` into an InputPlug, it whould then be serialized properly. You could even have a `foo` property to have the same accessability:

```python
class MyNode(INode):

    def __init__(self, foo, **kwargs):
        super(MyNode, self).__init__(**kwargs)
        InputPlug("foo", self, foo)
        InputPlug("input", self)
        OutputPlug("output", self)

    def compute(self, input):
        return {"output": "some output"}

    @property
    def foo(self):
        return self.inputs["foo"].value

ser = MyNode("bar").serialize()

deser = INode.deserialize(ser)
```

Or would that not be feasible for you?

**Comment by neuneck** [comment]
The `__init__` will not be called after the plugs get their values in the `post_deserialize` method, right? What I'm doing is I instantiate a client in the `__init__` and use that client in the `compute` method. 

Since my graph/nodes are single-use only, it should not matter much whether I instantiate a new client on every run of `compute`. Therefore, your suggestion might just work.

**Comment by neuneck** [comment]
Yes, definitely. I will check out if I can get what I want with subclassing `INode.serialize` - it might just work. If not, I'll have to do something so specialized to my use-case that it will make little sense to move that into flowpipe.
