### ISSUE TITLE
Graph.evaluate changes behaviour depending on `threaded` flag

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#79]
I just realized that the plain `Graph.evaluate(threaded=False)` evaluates all nodes independently of their dirty status. On the other hand `Graph.evaluate(threaded=True)` skips the evaluation of nodes that are not dirty.

I don't think that the `threaded` flag should change the evaluation behavior in this way. Moreover I think it makes a neat clarification to give the user explicit control over whether the entire graph is evaluated, or only the parts that are dirty.

I suggest extending the `Graph.evaluate` with a new optional keyword `skip_clean=False`. The default setting should reproduce current behavior, which is to evaluate all nodes. To achieve that for the threaded evaluation, I suggest adding a loop to `Graph._evaluate_threaded(..., skip_clean)` that explicitly sets all nodes/inputs to be dirty if `skip_clean` is set to `False`.

What's your opinions?

**Comment by PaulSchweizer** [comment]
Good point, we should make sure that both methods are aligned, thanks for spotting this! And yes I think we should do it the way you suggest.

**Comment by neuneck** [comment]
Changed tracked in https://github.com/PaulSchweizer/flowpipe/pull/86
