### ISSUE TITLE
Why not use pickle for graph or node serialization?

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#80]
I just found out that the python standard library module _pickle_ can easily create a binary representation of the entire graph, including its nodes, relations, internal state etc. 

Advantages I see are that
  * serialization and de-serialization are literal one-liners,
  * pickle smartly serializes individual objects only once, making sure not to duplicate, i.e. the `value` between an `OutputPlug` and its associated `InputPlug` instead keeping a reference to the original object, and
  * the requirements for pickle to serialize objects are rather easy to fulfill and as far as I'm aware most major libraries deliberately make sure to keep their main types picklable.

Disadvantages are that the resulting format is a non-human-readable binary that is python specific.

From my excursion into serializing the graph and its state so far, I would prefer using pickle as a serialization.

**Comment by PaulSchweizer** [comment]
Thanks for the investigation and the insights! 

You're right, we should rework the whole serialization a bit to allow for both json and pickle. I chose json at the time because I personally wanted that human-readability but of course it makes no sense to limit it to that.

I can also see other serialization formats, in fact we already have a ticket to serialize the graph to graphml #32 to make it viewable in existing applications like yEd. 

I think we should move the whole serialization code to a `serialization.py` and then provide the different options in there. I think simple functions would do, something as simple as this:

```python
def serialize_node_to_json(node):
    pass

def serialize_graph_to_json(graph):
    pass

def deserialize_node_from_json(node):
    pass

def serialize_node_to_pickle(node):
    pass

def serialize_node_from_pickle(graph):
    pass

# and so on ...
```

Would that be feasible for you?

**Comment by neuneck** [comment]
In general I think (de)serialization should stay bundled with the class itself. Serialization usually concerns the inner workings of a class as it has to be aware of the attributes that are necessary to ensure that a properly working instance is retreived after a round trip. At the same time, I see the charm in keeping the actual class clean of the lumps and bumps that come with a custom serialization scheme. Also, from my point of view the only class in flowpipe's inventory that is intended and well-suited to inherit from (in the user's codebase) is the INode.

All that being said, there might be a way of getting the best of both worlds:
I suggest we equip both, the `Graph` and the `INode` classes with a `X.serialize()` method and a `X.deserialize()` classmethod. The actual implementation takes place in the serialization submodule. The (de)serialize methods are just handlers that take a target format and redirect the call to the actual implementation.

A remaining question in any case would be whether to accept a file-like-object to write to / read from or whether the (de)serialization should return/accept a (byte)string. Again, both options could be done in unison by using the same interface the `json` or `pickle` modules offer, where there is a `dump`/`load` functionality expecting a stream to write to/read from and a `dumps`/`loads` functionality that returns the actual serialized representation.

**Comment by PaulSchweizer** [comment]
Thanks for the input! 

So it could look like this:

```python
class INode():

    def dump(self, datatype='json'):
        if datatype == 'json':
            return serialization.dump_node_json(data)
        # and so on for the other types and load
```

As for the file-like object, I think returning the `dumps` result should be fine for now. Currently we are also just returning a dict when serializing and it's up to the user to then store that to disk. 

```python
json.dump(MyNode().dumps('json'), '/tmp/my_node.json')
```

The other option would be to also have two methods `x.dumps` and `x.dump` (load/loads):

```python
MyNode().dumps('json')
MyNode().dump('json', '/tmp/my_node.json')
```

Or merging it into one `dump` function that, when given a file-object it uses it:

```python
def dump(self, datatype='json', file_object=None):
    if datatype == 'json':
        data = serialization.dump_node_json(data)
        if file_object:
            return json.dump(data, file_object)
        else:
            return data
```

I would go for the first approach, but please let me know what you think.

**Comment by neuneck** [comment]
@PaulSchweizer I started looking into your serialization and I learned a lot. I did not expect that one can do so much with introspection and smart usage of python's magics.

Unfortunately, I also realized how hard it is going to be to remove all that logic form the classes themselves. Going forward I would introduce the `dump(s)` methods and refer to your serialization methods if the json format has been chosen.

Given that pickling is really just a one-line call and is part of the standard library, I will just add the pickling inside the `dump(s)` methods as well.

**Comment by neuneck** [comment]
On second thought, the `json` and `pickle` library are focused on a specific format, which is where they use the `format.dump(s)` style for an encoding process. To get a feeling for what is usual when defining methods for encoding, I looked at numpy and pandas, and found that their central object have `to_<format>()` method.

In the spirit of keeping the API as intuitive as possible, I would like to follow that schema.

**Comment by PaulSchweizer** [comment]
That is indeed a better naming convention! 

Would that mean that we'd have a "to_json" and a "to_pickle" method in the INode?  That would interfere with our decision of having one "de/serialization" entry point, right?

**Comment by neuneck** [comment]
Indeed, but it seems to be the standard thing to do.

**Comment by PaulSchweizer** [comment]
Ok, then let's jump the bandwagon as well, thanks for researching this.

**Comment by neuneck** [comment]
Note: I realized that `FunctionNode` can not be pickled generally and nodes created with the `@Node` decorator can never be pickled. The reason is that their evaluation function is not defined at the top level of of a module and pickle can not handle closures.

See https://docs.python.org/3.7/library/pickle.html#pickle-picklable

**Comment by PaulSchweizer** [comment]
Thanks again @neuneck
