### ISSUE TITLE
How to access the different evaluation types

### ISSUE THREAD

**Issue by PaulSchweizer** [PaulSchweizer/flowpipe#82]
We now have three ways of evaluation: linear, multithreaed, multiprocessed.
Currently threaded and linear are available through `Graph.evaluate` whereas multiprocessing has it's own function `Graph.evaluate_multiprocessed`.
I'd like to consolidate this by having an evaluation function for each methodology.

I think the easiest would be to make `evaluate_threaded` public and deprecate the `threaded` option in `Graph.evaluate`:

```python
import warnings

class Graph(object):

    def evaluate(self, threaded=False, submission_delay=0.1, raise_after=None):
        """Evaluate linearly."""
        if threaded:
            warnings.DeprecationWarning("Please use Graph.evaluate_threaded instead.")

    def evaluate_threaded(self, submission_delay=0.1, raise_after=None):
        """Evaluate threaded."""

    def evaluate_multiprocessed(self, submission_delay=0.1):
        """Evaluate multiprocessed."""
```

What d'you guys think? Would that interfere with anyone's use-cases at the moment? Or would you prefer a different solution?

**Comment by neuneck** [comment]
Personally, I prefer a cleaner interface with more options in the call itself. So I would vote for a single entry point, such as

```python
class Graph(object):

    def evaluate(self, mode="linear", submission_delay=0.1, raise_after=None):
        """Evaluate the graph."""
        if mode == "linear":
            self._eval_linear()
        elif mode == "threading":
            self._eval_threaded(submission_delay, raise_after)
        elif mode == "multiprocessing":
            self._eval_multiprocessed(submission_delay, raise_after)
        else:
            raise ValueError("Invalid mode selected. Options are 'linear', 'threading' or 'multiprocessing'")
```
That way, users have a simple evaluation method at hand and the documentation can cleanly guide them through the options.

**Comment by Onandon11** [comment]
I agree with @neuneck, although we have to keep in mind that the options are clear and the function signature will not be enormous. A pro for neunecks' option is the fact that you can toggle the evaluation method easily with settings. 

In our repo we have quite a lot of nested Graphs'. Some of these graphs run in linear mode, others run in threaded mode. It's nice to have the option to toggle the execution methodology trough keyword arguments..

**Comment by PaulSchweizer** [comment]
Great, thanks for the input! Let's take @neuneck´s approach then.

**Comment by neuneck** [comment]
I will adapt the `evaluate_threaded` to match the behavior of plain `evalaute` anyways, so I can add this change on the same branch.

**Comment by neuneck** [comment]
Changed tracked in https://github.com/PaulSchweizer/flowpipe/pull/86
