### ISSUE TITLE
Multiprocessing test only works with submission_delay=0

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#85]
When working on the `Graph.evaluate` functionality, I found out that the current test
`test_multiprocessing_evaluation_updates_the_original_graph`
only runs successfully when the `submission_delay` parameter is set to `0`.

The pytest error is
[pytest_error.txt](https://github.com/PaulSchweizer/flowpipe/files/3717079/pytest_error.txt)

To reproduce, just execute `test_multiprocessing_evaluation_updates_the_original_graph` with a submission delay other than 0.

**Comment by PaulSchweizer** [comment]
Found the issue, I'll commit a PR later. Basically the check whether the upstreams are ready should only check whether one of the upstream nodes is still in `nodes_to_evaluate`.
