### ISSUE TITLE
Make the most important object available at the package level.

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#88]
When setting up a workflow with flowpipe I always import the classes
`Graph`, `INode`, `InputPlug`, `OutputPlug`
and need to add three imports to it. In order to do so, I need to understand something about flowpipe's internal structure.

It might be more convenient for users, if they could just do
`from flowpipe import Graph, INode, InputPlug, OutputPlug`.

To do so, we just need to add to `flowpipe/__init__.py`:
```python
from .graph import Grpah
from .node import INode, Node
from .plug import InputPlug, OutputPlug
```

Is there any objection to doing so?

**Comment by PaulSchweizer** [comment]
I like it, let's do it!

**Comment by neuneck** [comment]
Tracked in https://github.com/PaulSchweizer/flowpipe/pull/92
