### ISSUE TITLE
Have InputPlugs change is_dirty status only when newly set value is different from existing value

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#89]
In my workflow, I have to update the values of some input plugs, while other input plugs are unchanged. Rather than keeping track of what I need to change, I would prefer to simply assign the values and have the InputPlug figure out if the new value differs from the old one.

I suggest extending the `@value.setter` methods on all kinds of plugs to compare the newly set value to the existing value. This way, even if a plug is updated, only a real change of the value triggers the dirty status.

In more detail, I would opt for using a hash (sha256, or siphash if performance is relevant) of the new and old value and set the dirty status if the hashes differ.

**Comment by PaulSchweizer** [comment]
Also a good idea, let's do this!

**Comment by neuneck** [comment]
PR: https://github.com/PaulSchweizer/flowpipe/pull/91
