### ISSUE TITLE
Need guidance on publishing to PyPI

### ISSUE THREAD

**Issue by neuneck** [PaulSchweizer/flowpipe#90]
@PaulSchweizer You said to ping you if I need help with the release flow:

I merged the PR and then updated the version number in `flowpipe.__init__.py` on the master branch. I drafted a new release with tag `v0.5.5`.

The contributing.md mentions a way to trigger travis to release this. Do I need to click "publish release" for that to happen, or will I just release the old version with a new tag if I do this without having prompted the CI first?

How do I manually trigger a travis run, btw?

**Comment by PaulSchweizer** [comment]
sorry, I guess I'd need to be more specific about this, I'll update the contribution guide when I get the time for it. The only missing steps were:

1. Publish the github release, that will tag the commit which is then used in the build to determine whether to release to pypi
2. Travis should then trigger another build automatically
3. The py 3.6 build will publish to pypi

I was somehow confused and deleted the publish and the tag, so don't worry about that, it was me not remembering the steps anymore :D

Also, I'm not sure if you have the same rights on travis that I have in regards to flowpipe, let me know if you're missing options there (not sure if we can do anything about it though)

**Comment by neuneck** [comment]
It makes sense to have travis do the actual publishing - thanks for clarifying that!

I registered for travis and see the "restart build" button, so I think I should be fine in that regard.
