### ISSUE TITLE
Version 1.0.0

### ISSUE THREAD

**Issue by PaulSchweizer** [PaulSchweizer/flowpipe#98]
I'd like to set a roadmap for a version 1.0.0, now that the library is being used by a few more people.

What should be implemented for a v1.0.0 and which issues can wait for future releases?

I'd suggest to address these topics:

- #85 The multiprocessing bug
- #84 Subgraphs
- #17 Move docs to sphinx, maybe more generally updating and extending the documentation to include the topics that have come up and are not yet covered.

What do you think?

**Comment by neuneck** [comment]
Sounds good to me!

**Comment by neuneck** [comment]
When review your PR, I just wondered: Do we want to 

- Add official support for python 3.8?
- Set up an official schedule to phase out support for old python versions?

Especially the latter would be interesting, as python 2 will drop out of official support, and older 3.x versions don't support some features that would allow for neater syntax (esp. f-strings, introduced in python 3.6).

**Comment by PaulSchweizer** [comment]
Official support for py3.8 sounds good, we can just add it as a build target to travis.yml and see what happens to our tests :D

I'm a bit hesitant on phasing out py2.7 just yet though, I'd like to wait till next year and re-assess the situation then, currently we're still running on py2.7 and will do so at least for the first quarter of 2020. But after that yes, we should move away from supporting it and break free from these old and rusty shackles!

**Comment by Onandon11** [comment]
I think this is a great plan. But I think we also need to have somewhat of a timeline. I really need to plan thing to get things done, I don't know how it is for you guys. 

It also give somewhat more of a continuous improvement and focus (look at the number of issues currently are open 😄). Other projects have once every two weeks an update to a newer version, that gives something to work to.

**Comment by PaulSchweizer** [comment]
@Onandon11 , I like the idea of planning things out more. Do you have recommendations on which tools we should use or how we should go about this? Has anyone ever used the github project feature? Maybe we should give that a try?

**Comment by PaulSchweizer** [comment]
@Onandon11 , I now created a milestone for v1.0.0 https://github.com/PaulSchweizer/flowpipe/milestone/1
and a project kanban board for it:
https://github.com/PaulSchweizer/flowpipe/projects/1

Let me know what you think.

**Comment by PaulSchweizer** [comment]
I'm closing this ticket even though v1.0.0 is not ready yet. We have the milestone and the Kanban Project now so all the info for version 1.0.0 is tracked there now
